project:
  type: book
execute: 
  echo: false
  warning: false
  error: false
  freeze: auto
lang: es
book:
  title: "Tipologías de riesgo de protección integrada en contextos de crisis prolongadas"
  subtitle: "Un caso para Cisjordania"
  author: 
    - name: "Julian Ibarguen Onsurbe"
      affiliation: "Universidad Autónoma de Barcelona"
    - name: "Tutor: Pedro López-Roldan"
      affiliation: "Universidad Autónoma de Barcelona"
    - name: "Universidad Autónoma de Barcelona"
    - name: "Número de palabras: 20.000"
  date: 31/12/2022
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - c1_intro.qmd
    - c2_marco.qmd
    - c3_metodo.qmd
    - c4_resultado.qmd
    - c5_conclusion.qmd
    - c9_referencias.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    number-depth: 3
    fontfamily: libertinus
    colorlinks: true
    fig-pos: 'h'


