
word_sent <- dplyr::mutate(word_count, sentiment = dplyr::case_when(
    # Negative
    grepl("settle[rm]", word) ~ -1,
    grepl("uproot", word) ~ -1,
    grepl("wall", word) ~ -1,
    grepl("^ica$", word) ~ -1,
    grepl("israel", word) ~ -1,
    grepl("checkpoint", word) ~ -1,
    grepl("harass", word) ~ -1,
    grepl("occup", word) ~ -1,
    grepl("snakes", word) ~ -1,
    grepl("scorpions", word) ~ -1,
    grepl("disease", word) ~ -1,
    grepl("forces", word) ~ -1,
    grepl("overcrowd", word) ~ -1,
    grepl("soldier", word) ~ -1,
    grepl("unemploy", word) ~ -1,
    grepl("lack", word) ~ -1,
    grepl("^bad", word) ~ -1,
    grepl("violence", word) ~ -1,
    grepl("violat", word) ~ -1,
    grepl("suffer", word) ~ -1,
    grepl("assault", word) ~ -1,
    grepl("force", word) ~ -1,
    grepl("bypass", word) ~ -1,
    grepl("poor", word) ~ -1,
    grepl("risk", word) ~ -1,
    grepl("attack", word) ~ -1,
    grepl("tank", word) ~ -1,
    grepl("emergency", word) ~ -1,
    grepl("military", word) ~ -1,
    grepl("restrict", word) ~ -1,
    grepl("waste", word) ~ -1,
    grepl("expose", word) ~ -1,
    grepl("hazard", word) ~ -1,
    grepl("confiscate", word) ~ -1,
    grepl("unreg", word) ~ -1,
    grepl("muddy", word) ~ -1,
    grepl("defecat", word) ~ -1,
    grepl("threat", word) ~ -1,
    grepl("hinders", word) ~ -1,
    grepl("insufficient", word) ~ -1,
    grepl("impose", word) ~ -1,
    grepl("dangerous", word) ~ -1,
    grepl("excessive", word) ~ -1,
    grepl("hard", word) ~ -1,
    grepl("infect", word) ~ -1,
    grepl("invasion", word) ~ -1,
    grepl("difficult", word) ~ -1,
    grepl("danger", word) ~ -1,
    grepl("shortage", word) ~ -1,
    grepl("negative", word) ~ -1,
    grepl("accident", word) ~ -1,
    grepl("unsafe", word) ~ -1,
    grepl("prevent", word) ~ -1,
    grepl("cost", word) ~ -1,
    grepl("shortage", word) ~ -1,
    grepl("arrest", word) ~ -1,
    grepl("detain", word) ~ -1,
    grepl("inspect", word) ~ -1,
    grepl("displace", word) ~ -1,
    grepl("spoil", word) ~ -1,
    grepl("death|dead", word) ~ -1,
    grepl("deterior", word) ~ -1,
    grepl("bypass", word) ~ -1,
    grepl("defici", word) ~ -1,
    grepl("leak", word) ~ -1,
    grepl("unavail", word) ~ -1,
    grepl("burden", word) ~ -1,
    grepl("beat", word) ~ -1,
    grepl("disab[il]", word) ~ -1,
    grepl("^unprotect", word) ~ -1,
    grepl("separate", word) ~ -1,
    grepl("barrier", word) ~ -1,
    grepl("loss", word) ~ -1,
    grepl("afraid", word) ~ -1,
    grepl("evacuat", word) ~ -1,
    grepl("^hit$", word) ~ -1,
    grepl("mortal", word) ~ -1,
    grepl("demoli[st]", word) ~ -1,
    grepl("block", word) ~ -1,
    grepl("damage", word) ~ -1,
    grepl("annex.+", word) ~ -1,
    grepl("absen", word) ~ -1,
    grepl("critic", word) ~ -1,
    grepl("steal", word) ~ -1,
    grepl("cry", word) ~ -1,
    grepl("extreme", word) ~ -1,
    grepl("sexual", word) ~ -1,
    grepl("subjected", word) ~ -1,
    grepl("trench", word) ~ -1,
    # Positive
    grepl("light", word) ~ 1,
    grepl("facilitates", word) ~ 1,
    grepl("connect", word) ~ 1,
    grepl("train", word) ~ 1,
    grepl("^employ", word) ~ 1,
    grepl("coordinat", word) ~ 1,
    grepl("accommodat", word) ~ 1,
    grepl("accompan", word) ~ 1,
    grepl("rehabilit", word) ~ 1,
    grepl("solar|panels?", word) ~ 1,
    grepl("recieve", word) ~ 1,
    grepl("engage", word) ~ 1,
    grepl("provide|provision", word) ~ 1,
    grepl("protect", word) ~ 1,
    grepl("^safe", word) ~ 1,
    grepl("^digni", word) ~ 1,
    grepl("install", word) ~ 1,
    grepl("buil[dt]", word) ~ 1,
    grepl("efficient", word) ~ 1,
    grepl("improve", word) ~ 1,
    grepl("support", word) ~ 1,
    grepl("distrib", word) ~ 1,
    grepl("reparat", word) ~ 1,
    grepl("willing", word) ~ 1,
    grepl("mainten", word) ~ 1,
    grepl("paved", word) ~ 1,
    grepl("deliver", word) ~ 1,
    grepl("construct", word) ~ 1,
    grepl("^registr", word) ~ 1,
    grepl("fix", word) ~ 1,
    grepl("project", word) ~ 1,
    grepl("service|serve", word) ~ 1,
    grepl("i?ngo", word) ~ 1,
    grepl("^sufficient", word) ~ -1,
    grepl("aware", word) ~ -1,
    grepl("function", word) ~ -1,
    grepl("secure", word) ~ -1,
    grepl("suppl[iy]", word) ~ -1,
    grepl("inform|notif[yi]", word) ~ -1,
    grepl("^know", word) ~ -1,
    grepl("efficien", word) ~ -1,
    grepl("^fill", word) ~ -1,
    grepl("adapt", word) ~ -1,
    grepl("partner", word) ~ -1,
    grepl("adequat", word) ~ -1,
    grepl("activity", word) ~ -1,
    grepl("implement", word) ~ -1,
    grepl("product", word) ~ -1,
    grepl("renew", word) ~ -1,
    grepl("accessing", word) ~ -1,
    grepl("milk|dairy|sheep|bees|cook|solar|panel|olive|donkey", word) ~ -1,
    TRUE ~ 0))

word_sent <- dplyr::filter(word_sent, sentiment != 0) |>
  dplyr::mutate(sentiment_cat = as.factor(dplyr::case_when(
    sentiment < 0 ~ "negativo", sentiment > 0 ~ "positivo", TRUE ~ NA_character_
  ))) 
  





