# Introducción

## Crisis perpetuadas y Protección Integrada
Hoy en día las crisis perpetuadas (_protracted crisis_) dominan el escenario de la acción humanitaria: Haití, Palestina, Somalia, Sudan de Sur, Siria y más. Todas ellas, crisis que se alargan por décadas y donde la realidad social ha sufrido una transformación estructural desde que comenzó la crisis. En estos escenarios de crisis perpetuadas la sociedad se ha adaptado a la crisis. Pensemos en el tifón Yolanda que arraso Filipinas. Tras unos años de respuesta humanitaria, y a pesar sus consecuencias e impacto, la sociedad filipina se mantiene estable en su esencia: los valores, las instituciones, las relaciones sociales se han mantenido estables adaptándose al cambio que supuso Yolanda y su respuesta. Sin embargo, no olvidemos la crisis de Haití, donde en 2010 un terremoto devastó no solo la infraestructura, pero todo el tejido social e institucional que hacen de Haití, hoy en día, un escenario de crisis perpetuada.

Desde una perspectiva de sistemas, en las crisis perpetuadas, transforman el sistema en su totalidad, más aún, el sistema se reencuentra consigo mismo, retornando a un estado de homeostasis que paradójicamente representa un contexto hostil y volátil: el sistema se ha adaptado a la crisis. La economía, la demografía, la cultura, las redes sociales, las instituciones y todo ha encontrado su estabilidad en este escenario de crisis… Y, como todo sistema estabilizado, muestra resistencias al cambio. Paradójicamente, necesitaría una nueva crisis para cambiar. 

En estos escenarios de crisis perpetuada nos encontramos con una vulneración de derechos sistemática en un ambiente coercitivo por la violencia, la degradación de las condiciones de vida, la violenta transformación de la estructura social y —en muchas ocasiones— por la propia acción institucional. Es entonces que surge el concepto de protección integrada para dar respuesta a una violación de derechos sistémica y estructural. 

Desde la perspectiva tradicional de la intervención en protección las acciones se dirigían a áreas específicas como violencia de género, explotación infantil, arrestos extrajudiciales, registro de personas desplazadas, documentación. Ahora, con el concepto de protección integrada, comprende tanto las acciones de la perspectiva tradicional, como cualquier otra acción destinada a proteger los derechos y el acceso pleno a los servicios. Por ejemplo, construir un pozo para reducir la distancia recorrida para acceder al agua y por tanto la exposición a las amenazas de un ambiente hostil [@dg-echo_humanitarian_2009].

## Repensando la Acción Humanitaria
En las crisis perpetuadas el sistema, transformado en su totalidad, se ha rencontrado consigo mismo y ha retornado a la homeostasis en un contexto hostil y volátil: se ha adaptado a la crisis. La economía, la demografía, la cultura, las redes sociales, las instituciones y todo ha encontrado su estabilidad en este escenario… Y, claro, no quiere cambiar, mostrando la resistencia al cambio de todo sistema. Paradójicamente, necesitaría una nueva crisis para cambiar. Muy probablemente la Acción Humanitaria haya contribuido muy poco —o más bien nada, sino todo lo contrario— a evitar que estas crisis se prolongaran en el tiempo. Desde una perspectiva cortoplacista y asistencialista, carente de visión estratégica e innovación, la Acción Humanitaria se ha limitado a entregar los bienes básicos necesarios para la supervivencia. Así, justificando que no es competencia de la Acción Humanitaria lo que corresponde a la nación —sociedad y estado— que por otra parte esta vulnerada y des-empoderada en un contexto de cambio violento y estructural.

Ante el fracaso evidente de la no-estrategia, en la última década han surgido nuevos conceptos estratégicos: _durable solutions_ y _Nexus_ institucionalizados por el @inter-agency_standing_committee_iasc_2010 y @inter-agency_standing_committee_task_2016 respectivamente. De estos conceptos estratégicos se desprenden además los conceptos operativos de transversalidad, participación y empoderamiento. El sistema de clústeres que ha gobernado —y compartimentado— la Acción Humanitaria desde 1991 se desmorona incapaz de integrar los conceptos emergentes, ni operativamente, ni teóricamente. Todo ello, a pesar de su revisión en 2005 que creo un nuevo nivel "global" para el sistema de clústeres [@inter-agency_standing_committee_guidance_2006]. Con estos nuevos conceptos, se estaba reformulando una nueva la Acción Humanitaria: 

Con el concepto de _Nexus_ se vinculaba Acción Humanitaria y Desarrollo: lo que siempre se había planteado como un binomio, hoy en día se entiende desde una perspectiva de la lógica borrosa (Kosko, 2000, citado por @amoros_prospectiva_2011). Como una escala de grises en la que se enmarcan acciones que encaminan a una sociedad en crisis, a una situación estable en la cual se ha resurgido con mayor capacidad y resiliencia frente a futuros eventos de crisis. Se abre la puerta a la visión estratégica y de largo plazo.

Con el concepto de _Durable solutions_ se replanteaba la acción, que no debe ya estar centrada en cubrir inmediata y básicamente necesidades (no confundir con necesidades básicas e inmediatas), sino en proveer de la estructura para la satisfacción sostenible de las necesidades. 

Con el concepto de **Transversalidad** se daba paso a la complejidad, se entiende la realidad liquida que necesita acciones transversales, que impacten múltiples dimensiones simultáneamente. El sistema de clústeres limita la comprensión de la complejidad y más aun limita la acción transversal. Encasillado en sus sectores el sistema de clústeres no es capaz de entender que la acción en un sector repercutirá en otro sector, y la compartimentación en silos impide identificar, comprender y responder a la complejidad. Se abre la puerta al holismo y a la creatividad.

Con el concepto de **Participación** se planteaban cuestiones éticas evidentes, y permite a la Acción Humanitaria superar su dilema: como plantear acciones estratégicas y a largo plazo sin caer en el poscolonialismo: involucrando a la nación receptora de Acción Humanitaria. Al promover la participación, tanto en el diagnostico como en la respuesta, la nación receptora de la Acción Humanitaria se ve involucrada en los procesos de la Acción Humanitaria. Se abre la puerta a lo local, lo global ya lo trae la Acción Humanitaria.

Con el concepto de **Empoderamiento** se iba más allá de la participación. No basta con estar involucrada, debe tener poder para influir en la toma de decisiones. Debe estar capacitada y autorizada para definir, juntamente con los actores externos que despliegan la Acción Humanitaria, el diagnóstico y la respuesta. La sociedad en crisis debe incrementar su control sobre la situación de incertidumbre que genera el despliegue de millones de dólares y miles de extranjeros en su nación. Se abre a puerta a la apropiación de la acción.

## Una cultura de innovación humanitaria 
Estos nuevos conceptos abrían la puerta a las cinco condiciones para una cultura de innovación [@amoros_educar_2014]: pragmatismo, contextualización, sostenibilidad, visión global y visión estratégica. En este nuevo escenario la Acción Humanitaria encuentra un marco conceptual propicio para desarrollar una cultura de innovación, que no solo beneficiaría a la efectividad y eficiencia de la Acción Humanitaria, sino también a las naciones donde se implementa. Los siete pilares planteados por @amoros_prospectiva_2011 que sostienen la cultura de innovación, encajaban la nueva acción Humanitaria que se dibuja y los beneficios que trae para la misma acción y para la nación en la que se implementa:

**Holismo**. Enlaza directamente con el concepto de transversalidad en la Acción Humanitaria. Para desarrollar una acción transversal que genere impactos esperados y en cadena a través de múltiples dimensiones y niveles es necesario tener un entendimiento holístico de la realidad. Solo así se puede aprehender la realidad en su totalidad y desarrollar acción que vayan más allá de la provisión de bienes básicos y que tengan un impacto estratégico y trascendente al momento en el que se implementa, permitiendo conectar con las Acciones de Desarrollo. Ahora bien, para alcanzar un entendimiento lo más holista posible, es condición necesaria la participación de la propia sociedad en la que se actúa. Sin ella no es posible aprehender la complejidad de la realidad; la sociedad local ofrece profundidad, los actores humanitarios ofrecen objetividad.

**Heterodoxia**. Todavía existe en la Acción Humanitaria una preferencia por los métodos cuantitativos, pues son los que son capaces de contar a los beneficiarios y monetizar la ayuda de manera más eficaz, y no necesariamente porque provean de la información necesaria para una ayuda más eficaz. No es que no sean necesarios, es que son insuficientes. En cualquier caso, poco a poco van apareciendo más evaluaciones de necesidades basadas en métodos cualitativos, si más bien por la aparente economía de los métodos cualitativos sobre los cuantitativos. De una forma u otra, poco a poco van mostrando su utilidad, y en especial su capacidad para ofrecer una diagnostico holístico de la realidad. Entre otras ventajas los métodos cualitativos dan cabida a la participación de la sociedad local, más allá de convertirlos en una mera fuente de información. Metodologías de Investigación, Acción y Participación (IAP) se vuelve idóneas en este escenario, ya que cualquier investigación o acción promovida por los actores humanitarios extranjeros carecerá de sentido sin la participación de la sociedad local. La heterodoxia a través de la IAP como método junta la sistematización para un conocimiento riguroso de la realidad, a la vez que la creatividad para el desarrollo de acción innovadoras; todo ello promoviendo la participación y el empoderamiento.

**Relativismo**. Con la mayor diversidad en las metodologías aplicadas, y la realización de que los métodos cuantitativos son falibles cuando se consideran absolutos —que no lo son, ni lo pretenden; no deberían— se empieza a entender que la comprensión de la realidad dependen de su interpretación y del método utilizado para alcanzar el diagnostico. Que todo depende del objeto, y que hay objetos y niveles de conocimiento más susceptibles de ser aprehendidos por métodos cuantitativos y otros por métodos cualitativos. Entonces, si la interpretación es un elemento tan importante para el comprender la realidad en la que se actúa, la participación de la sociedad en la que se actúa se convierte en un elemento esencial para acercarnos a un entendimiento contextualizado. Este conocimiento local, se verá complementado con la mirada global que ofrecen los actores humanitarios.

**Incertidumbre**. Si todo es relativo, entonces la incertidumbre es inevitable; y si hay incertidumbre, no es posible una clasificación exacta de la realidad. Se impone una lógica borrosa que implica, no solo que la realidad no se pueda describir en clave dicotómica, si no que su ordenación en categorías y tipologías debe ser entendida entendidas como permeables; lo que nos lleva de vuelta al concepto de transversalidad. Así, la realidad puede ser clasificada de una manera y otra, pues su interpretación es relativa y la incertidumbre no permite prever exactamente en que resultara. Ahora bien, esto no quiere decir que el desarrollo de tipologías sea en vano, ni que ante la incertidumbre no se puede actuar. Mas aun, es la incertidumbre lo que abre las puertas al cambio. Es, de hecho, la incertidumbre la que ha provocado la crisis que requiere la Acción Humanitaria, y ella debe contribuir a reducirla por medio de la comprensión de la realidad y su acción sobre ella.

**Estructuralismo**. Puesto que todo es incierto los escenarios posibles son múltiples. La reducción de la realidad desde la aproximación funcionalista limita su comprensión. El estructuralismo y su lógica inductiva –y abductiva– promueve el conocimiento holístico e interpretativo. Desde el estructuralismo no se plantea una visión reducida – única posibilidad, la más probable– sino la presentación de todas aquellas que puedan ser concebidas e interpretadas. Ya hablamos detenidamente sobre este punto en nuestro primer ensayo, quizás resaltar ahora la importancia que tiene abrir el abanico del futuro para el empoderamiento: Si existen varias posibilidades de futuro y la acción puede encaminarnos a una de ellas entonces solo debemos elegir cual y actuar en consecuencia para tratar de alcanzarlo”. Esto devuelve la propiedad a la nación en crisis sobre qué futuro elegir, y las acciones que la encaminaran.

**Proactivismo**. Entonces, el cambio no es una cuestión de si sí, es una cuestión de cómo y hacia donde: el cómo dependerá la balanza entre incertidumbre y control, que se alcanza con el conocimiento de la realidad; el hacia donde dependerá de la proyección de ese conocimiento hacia el futuro en forma de identificación de amenazas y oportunidades. Solo así se puede plantear una visión estratégica, un plan a largo plazo de hacia dónde se quiere cambiar y cómo alcanzarlo. Ahora bien, reincidimos en la importancia de la participación y el empoderamiento. La actitud proactiva debe ser compartida tanto por los actores humanitarios, como por la nación en la que se desarrolla la acción humanitaria. La Acción Humanitaria tiene la responsabilidad de superar la reactividad que solo promueve la extensión en el tiempo de la crisis -_protracted crisis_- y hacerlo de una manera participativa y emancipadora. Por su parte, la nación en crisis tiene la responsabilidad de tomar el control de su futuro empoderándose y apropiándose de él; no solo de hacia dónde quiere llegar, si no de las acciones que realizará para alcanzarlo. La acción Humanitaria es un soporte, un elemento de estabilidad en un escenario altamente incierto que incrementa el control, un control que debe ser utilizado como un catalizador para el empoderamiento, y no para el cambio. El cambio debe provenir de la nación en crisis.

**Visión Prospectiva**. Todos los pilares que hasta ahora hemos desarrollado son condiciones necesarias para una cultura de innovación, pero no suficientes, ni por sí solas, ni como grupo. El conocimiento holístico de la realidad actual que ofrece la heterodoxia metodológica; la proyección de la realidad presente aprehendida, diversa y relativa que abre un abanico de posibles escenarios; la superación del miedo a la incertidumbre que abre la puerta al cambio; la actitud proactiva que genera apropiación y control sobre el cambio. Todos ellos sustentan la visión prospectiva. Pero para alcanzar una cultura de innovación todo ello debe ser procesado desde la visión prospectiva por medio del pensamiento complejo, el pensamiento crítico, el pensamiento creativo, el pensamiento constructivo y el pensamiento estratégico. Es solo así que todo lo anterior genera una cultura de innovación que pone en relación sinérgica investigación, desarrollo, innovación y diseño.

La cultura de innovación de la mano de la prospectiva como herramienta promueve una Acción Humanitaria estratégica (presente), que enlaza con la Acción de Desarrollo (futuro), y que devuelva a las naciones en crisis su poder para determinar su propio devenir. Las metodologías de IAP se ofrecen como complemento sinérgico a la prospectiva. Estas pueden canalizar la acción estratégica e innovadora, a la vez que proveer del entendimiento necesario del presente para el desarrollo de escenarios futuros. Estos escenarios futuros vuelven a retroalimentar la acción estratégica de la IAP. En definitiva, permitiría desarrollar el potencial emancipador de la Acción Humanitaria sobre las naciones en las que se implementa para que, de una vez por todas, no sea necesaria.  

## Enfoque de Protección Comunitaria
El Enfoque de Protección Comunitario (EPC) desarrollado por @we_world_guidelines_2019 es una herramienta de movilización y empoderamiento comunitario usada para diseñar Programas de Protección Integrada que abarcan intervenciones humanitarias y de desarrollo, dando respuesta al Nexo en la acción humanitaria. Además, provee de procesos y herramientas para facilitar la coordinación y complementariedad entre diferentes actores de acción humanitaria y desarrollo para encontrar soluciones duraderas a las problemáticas de las poblaciones afectadas. 

En el marco de la EPC se identifican tres componentes clave en su corpus metodológico: 1) El Cuestionario Multi-Sectorial, una entrevista estructurada de preguntas cerradas a una muestra propositiva seleccionada por muestreo socio-estructural; 2) la Perspectiva Comunitaria Narrada, una serie de grupos de discusión y entrevistas en profundidad a perfiles vulnerables dentro de la comunidad; y 3) el Enfoque Individual de Protección, un mecanismo operativo para identificar, evaluar y referir casos con necesidades de protección inmediata @we_world_guidelines_2019. De la interrelación de los componentes de la metodología, el EPC se inspira en las teorías de protección en acción humanitaria para crear un sistema de análisis con un enfoque de derechos y centrado en la comunidad como unidad de análisis. De esto se desprenden dos productos principales de la metodología: los Perfiles Comunitarios y los Planes de Protección Integrada.

De las definiciones provistas por @marti_investigacion-accion_2016 y @schoonenboom_how_2017, el EPC se puede clasificar como una metodología: 1) Participativa, por medio del proceso de implementaciones inician dinámicas participativas y de restitución de resultados; 2) Multinivel, dado que contiene herramientas para evaluar tanto al contexto comunitario, como a sus individuos; 3) Mixta, de articulación secuencial y dependiente (CUAN -> CUAL) que otorga igual importancia a técnicas cuantitativas y cuantitativas.

El EPC responde en gran parte a las necesidades para una acción humanitaria basada en la innovación y que da respuesta a los conceptos de _Nexus_, _Durable Solutions_ y transversalidad. Sin embargo, su aplicación requiere de substantivos recursos, no tanto materiales como humanos y de capacidades, que rara vez están disponibles en las organizaciones humanitarias, y aun menos se pueden aplicar de forma generalizada sobre un contexto humanitario. Surgen entonces la necesidad de encontrar alternativas menos demandantes, que pueden ofrecer una visión general pero explicativa del contexto que puede informar de área o tipos prioritarios sobre los cuales aplicar metodologías como el EPC 

##	El caso de Cisjordania
La región de Cisjordania, en los territorios ocupados Palestinos, esta sumergida en una crisis crónica que dura ya más de 50 años, con consecuencias humanitarias. Dentro del mundo humanitario, Palestina representa una de las crisis perpetuadas más particulares, con su particular contexto político, su larga duración y resultado de la falta de cumplimiento de la ley internacional por parte de poder ocupante. Palestina continúa enfrentado serias amenazas de protección como es la destrucción y daño de la propiedad, desplazamientos forzados, restricciones a la libertada de movimiento y al acceso de servicios esenciales. Todo ello con el consecuente deterioro de las condiciones de vida. Para Jerusalén Este, la revocación del derecho al permiso de residencia se convierte en un desencadenante del desplazamiento forzado. Este escenario político e institucional se ve exacerbado por una crisis social sumida en la violencia entre los colonos israelíes y los palestinos, todo ello vinculado la expansión de los asentamientos israelís en Cisjordania. 

Representado la dimensión y actualidad de la problemática. En 2022, un total de 950 estructuras palestinas fueron demolidas, confiscadas o sujetas a desahucio por parte del estado de Israel; entre ellas, 140 fueron construidas con donaciones de la acción humanitaria y 193 eras viviendas residenciales [@un_ocha_occupied_2022-1].  En total, se vieron forzosamente desplazadas 1.022 personas, con un total de 28.448 personas afectadas [@un_ocha_occupied_2022-1]. En su dimensión social, en 2022 en Cisjordania, hubo un total de 153 palestinos fallecidos y 10.066 heridos en eventos relacionados con protestas, violencia de colonos y conflictos sociales. Para los israelís este número representaba a 21 personas fallecidas y 251 heridos [@un_ocha_occupied_2022]. Mas aun, en este escenario, el @global_protection_cluster_protection_2022 refiere un deterioro generalizado de la salud mental en la infancia palestina, la cual sufre ya una de las más deterioradas en el Este del mediterráneo con un 54% de niños y un 47% de niñas con un desorden de salud mental.

En este escenario coercitivo, las necesidades humanitarias se hacen crónicas a un nivel intermedio entre la satisfacción y la insatisfacción de las mismas. Especialmente, en los sectores de la seguridad alimentaria, el agua, saneamientos e higiene, la educación, la salud entre otras áreas de desarrollo social donde no encontramos escenarios drásticos y calamitosos, pero las necesidades quedan en general insatisfechas, estancadas. Así, se ven manifestaciones de esta coerción en los movimientos forzados de población a través de la demolición de viviendas y desahucios; la restricción de acceso a medios de vida y recursos; explotación y puesta en peligro de los recursos naturales; destrucción y confiscación de propiedad y tierra publica; expansión de las colonias y la proliferación de conflicto y violencia social asociadas. Todo ello deriva en un deterioro de las condiciones socioeconómicas de la población palestina y en barreras para su desarrollo [@un_secretary-general_economic_2018].

Estos factores son aún más evidentes en la definida área C, creada por el Acuerdo Interino de Oslo firmado en 1995 y más conocido como Oslo II (@fig-oslo_map). Con estos acuerdos, la región de Cisjordania quedo dividida en tres áreas para un periodo de transición de autoridad hacia la autoridad Palestina. El área A quedaba bajo completa administración civil y militar por parte de la Autoridad Palestina; El área B, la administración civil quedaba bajo la Autoridad Palestina, pero la administración militar recayó en las autoridades israelís; el área C queda bajo completa administración israelí, tanto civil como militar [@israeli_ministry_of_foreing_affairs_israeli-palestinian_1995]. Las restricciones impuestas en el área impiden la planificación y zonificación para cualquier desarrollo en esta área. Autoriza además la destrucción de la propiedad privada y la expropiación de tierras, impidiendo la rehabilitación o construcción de infraestructura básica y servicios esenciales

```{r} 
#| label: fig-oslo_map
#| fig-cap: "Mapa de Cisjordania con areas Oslo. Par aun mapa mas detallado: https://www.ochaopt.org/content/west-bank-access-restrictions-june-2020"
#| fig-cap-location: bottom
#| layout: [[100]]
#| fig-width: 15
#| fig-height: 15

p_wb_oslo <- tmap::tm_shape(oslo) + #, bbox = bbox_new) +
  tmap::tm_style("classic") +
  tmap::tm_polygons("CLASS", style = "cat") +
  tmap::tm_layout(legend.outside = TRUE,
    legend.position = c("right", "top"))+ 
  tmap::tm_shape(adm2) +
  tmap::tm_borders() +
  tmap::tm_layout(frame = FALSE)
p_wb_oslo  # print
```

Palestina representa una crisis donde quizás las necesidades humanitarias más básicas no se agudizan y alcanzan los extremos de otras crisis de emergencia, pero donde la necesidad de protección se ve sistemáticamente vulneradas por el contexto político y social al que se ve sometido la población palestina, encubriendo la posibilidad de desarrollo y sostenibilidad. La situación humanitaria en la región ha sido descrita por el _Humanitarian Country Team_ de las Naciones Unidas como una crisis prolongada de protección derivada de la falta de cumplimiento del poder ocupante para responder y comprometerse con la Ley Internacional Humanitaria y la ley Internacional de Derechos Humanos [@un_ocha_humanitarian_2016]. El _Humanitarian Country Team_ se desplego en 2008 en los territorios Palestinos, formados por diferentes actores humanitarios para dar respuesta a las crisis generadas por las intifadas en Gaza y para paliar el deterioro socioeconómico en la región de Cisjordania. 

## Justificación
Sobre las bases de la nueva acción humanitaria, y construyendo sobre los desarrollos de la metodología del EPC para operacionalizarla, nuestra tesis pretende aportar dos desarrollos metodológicos que contribuyan a un primer análisis explicativo del contexto. Si bien, dado la limitación de recursos y la complejidad de los contextos humanitarios, cualquier análisis inicial debe ser suficientemente ligero, practico y sistemático para ser implementado en contextos con limitados recursos y capacidades, y una presión humanitaria sobre el tiempo.

Con todo, proponemos un desarrollo metodológico mixto que se nutre de fuentes secundarias comunes en la acción humanitaria y que generan resultados descriptivos y explicativos, y a su vez sintéticos y sistemáticos. La metodología consta de dos partes: 1) la construcción de un sistema de indicadores y su agregación a un índice compuesto que facilite la identificación y análisis sintético de una problemática multidimensional y compleja como son los riesgos de protección en contextos de crisis perpetuadas. 2) La articulación de una tipología de riesgos de protección que añada valor explicativo al índice de protección, y sea complementado con información cualitativa.

El índice compuesto sirve de instrumento para la descripción y visualización de la problemática compleja de forma sintética, y que pueda ser utilizada para guiar la movilización de recursos y mensajes de incidencia política. La tipología permite guiar una intervención más eficiente centrada en problemáticas comunes, lo que permitirá el diseño de intervenciones “mancomunadas” a nivel territorial y de perfiles sociodemográficos.
