
# Conclusión

Con este trabajo propusimos la construcción de una tipología de riesgo de protección, complementada con un índice compuesto del riesgo de protección y una profundización cualitativa. Estos tres análisis complementarios tenían como objetivo proponer una medición sintética del riesgo de protección que puede ser desarrollado por organización humanitarias con capacidades limitadas. Este índice serviría para guiar los programas de protección apuntando a la distribución geográfica del riesgo y a un análisis cruzado con otras variables demográficas que permita caracterizar el riesgo de protección en un determinado contexto. A su vez, identificar una tipología que añadiera valor explicativo al fenómeno del riesgo de protección, identificando "tipos ideales" descritos a partir de su parangón, y que permitan agrupar unidades observadas con riesgos similares. Esta agrupación ayudará a especificar los programas de protección a aspectos concretos del riesgo de protección, no dependiendo de la distribución geográfico, sino exclusivamente de las características del riesgo de protección. Así, se podrían definir programas tipo para responder a estas problemáticas tipo. Finalmente, la profundización cualitativa pretendía hacer uso de un activo de información cualitativo común en las organizaciones humanitarias y que sin embargo se usa poco para el análisis del riesgo de protección. Por medio de estas profundizaciones aplicamos un análisis de sentimientos y coocurrencia a información extraída de los grupos de discusión de para describir situaciones específicas que se enmarcan en las problemáticas definidas por las tipologías de protección. Etas profundización, permitirá obtener el nivel necesario de detalle para plantear actividades concretas dentro de los programas de protección que den respuesta a estas situaciones.

Para el índice compuesto se utilizaron los datos de una evaluación multisectorial de necesidades realizada en el año 2022, entrevistando a hogares de palestina. Con las entrevistas recogidas para Cisjordania, creamos una serie de indicadores que representaran el riesgo de protección, basándonos en los marcos teóricos desarrollados y en estándares internacionales, siempre que estuvieran disponibles. Los indicadores quedaban formulados en forma binaria, siendo el valor positivo representando la presencia del atributo de riesgo de protección, mientras que el valor cero representaba la ausencia del atributo.  Tras imputar valores perdido por el método de _hot-deck_, aplicamos un ACM para identificar las dimensiones latentes e interpretarlas con el marco teórico existente para el riesgo de protección. Así, resulto que la primera dimensión señalaba el riesgo de protección, agrupando en el eje de coordenadas positivo todas las categorías que representaban riesgo de protección, y en el eje de coordinadas negativo todas las que representaban la ausencia de riesgo de protección. A su vez, la segunda dimensión estaba capturando el eje de Seguridad y Dignidad, al posicionar los indicadores más relacionados con la seguridad en el eje positivo, mientras posicionaba a los indicadores relacionados con la dignidad en el eje negativos.

Una vez interpretadas estas dimensiones, se evaluó la importancia de los indicadores para la composición de las dimensiones latentes. Se eliminaron aquellos que no contribuían empíricamente y cuya aportación teórica no era relevante, aplicando el principio de parsimonia y simplificando el modelo. Tras volver aplicar el ACM con los indicadores finales, se calculó el índice de protección seleccionando todos los indicadores significativamente relevantes para la primera dimensión. Para agregar el indicador se utilizó la media ponderada, usando para los pesos los eigenvalues de la primera dimensión correspondientes a cada indicador. El índice compuesto de riesgo de protección representaba así la proporción de atributos de riesgo de protección que un hogar poseía, ponderada según su el nivel de contribución de cada atributo a conformar el riesgo de protección. además de proponer un índice con una definición e interpretación clara, este permitió el cruce con otras variables para explorar la distribución geográfica del riesgo de protección y sus características esenciales. Resulto de este análisis descriptivo del riesgo de protección que las áreas con más riesgo eran los campos de refugiados palestinos y el área Oslo C. 

Partiendo del último ACM realizado para la composición del índice de riesgo de protección, aplicamos el análisis de tipologías. El proceso metodológico aplicado constituye en sí mismo un análisis y una estructuración de la realidad de Cisjordania entorno a los marcos teóricos del sector de la protección en la acción humanitaria. Durante el proceso de análisis se pudo observar cómo riesgo de protección, seguridad y dignidad, conceptos eminentemente teóricos, emanan de los datos empíricos y cristalizaron en una tipología derivada de la articulación entre interpretación teórica y validación empírica. Para ejecutar el análisis de tipologías aplicamos un ACL siguiendo el método de _k-means_ jerárquico, siendo este el que mejor resultados daba tanto empíricamente como teóricamente. Con la combinación del ACM y el ACL fue posible estructurar un espacio dimensional en que posicionar los diferentes conceptos teóricos y extraer una tipología de riesgo de protección fragmentada en tres tipos ideales o parangones: 

1. El primer tipo era el mayoritario (2.207 hogares), y representaba a los hogares con **menor riesgo de protección**. Este tipo no se veía gravemente afectado ni por factores de seguridad, ni por factores relacionados con la dignidad.
2. El segundo tipo comprendía a 871 hogares, representando a los hogares con **riesgos de protección relacionados con la dignidad**.Al contrario que el primer tipo, este segundo tipo si se ve afectado de manera relevante por el riesgo de protección.
3. El tercer tipo incluía a 310 hogares, y representaba a los hogares con **riesgos de protección relacionados con la seguridad**. Este tipo era el que mayor riesgo de protección presentaba. El hecho de que el riesgo de protección se presente con mayor intensidad en este grupo, se alinearía con el concepto de que la seguridad es condición necesaria para la dignidad, si bien no al revés.

Analizando la distribución geográfica de la tipología de los riesgos de protección, se ha podido observar una distribución homogénea en términos generales homogéneas, si bien se pueden identificar algunos patrones. Mientras que el tipo de riesgo de protección relacionado con la dignidad se concentraba mayoritariamente en Nablus y Qalqiliya, y en campos de refugiados palestinos; el tipo de riesgo relacionado con la seguridad se concentraba en el área Oslo C.  

Con todo, los estratos que podrían derivarse de la tipología podrían aplicarse a la estratificación de un diseño de encuesta con el objetivo de explorar y analizar más a fondo los desafíos de protección en Cisjordania. De esta forma se podría desarrollar un diseño muestral más eficiente al reducir la varianza interna de los estratos; cada uno de ellos constituiría una unidad autónoma de análisis. El procedimiento desarrollado que se aplica en el presente documento podría aplicarse a entidades administrativas superiores distintas del hogar, como por ejemplo áreas censales o localidades, promediando los valores de todas las comunidades comprendidas por la unidad administrativa superior. De esta manera, se podrían desarrollar tipologías a diferentes niveles administrativos para comprender mejor cómo se distribuyen los desafíos de protección en el espacio geográfico y explorar si la combinación de los desafíos de protección en una serie de comunidades formó nuevos tipos. 

Una vez desarrollada la tipología nos servimos de la información cualitativa recogida por medio de grupos de discusión a los beneficiarios de organizaciones humanitarias. Esta información había sido capturada por medio de cuadernos de campos y clasificada por un proceso de codificación guiado con un programa específico. Las comunidades abarcadas por los grupos de discusión se encontraban en el área Oslo C, lo que permitía realizar la profundización cualitativa sobre la tipología de riesgo relacionada con la seguridad. Para ello se aplicaron dos análisis provenientes de la minería de datos: el análisis de sentimiento y el análisis de coocurrencias. Esto análisis permitieron, por un lado, servirse de un recurso poco utilizado en la acción humanitaria para estos propósitos, por otro dar valor explicativo a una tipología concreta del riesgo de protección, identificando situaciones específicas que enfrentan los hogares de esta tipología. Así, el análisis de sentimiento mostro un sentimiento neto negativo generalizado para la gran mayoría de las localidades. Este se reflejaba en palabras negativas como _"lack"_, _"colonos"_, _"israeli"_, entre otras. Las pocas palabras positivas que se encontraban en el discurso se referían sobre todo a la ayuda provista por las organizaciones humanitarias: _"services"_, _"rehabilidation"_, _"connected"_, entre otras. 

Mientras que este análisis mostraba sentimiento generalizado de los hogares entrevistados, así como daba pistas de las razones, aun no identificaba situaciones o problemáticas concretas enfrentadas por estos hogares. El análisis de coocurrencias proveyó esta mirada. Así, usando el _bigram_ como unidad de análisis pudimos trazar redes conceptuales que vinculaban palabras entre sí. Por medio de la interpretación de estas redes se podían describir situaciones concretas. Mas aun, estas situaciones podían ser validades midiendo la fuerza de la correlación entre las diferentes palabras coocurrente. Así, identificamos que la presencia de colonos y asentamiento israelís, sumado a las restricciones de movimiento y la falta de alternativas de _by-pass_, suponen una barrera para la poblacion palestina para acceder a servicios básicos como son la saludo -incluidos servicios primarios y de emergencia- y la educación. La localización de las localidades en el área Oslo C, y los deficiente transporte públicos, provocan tiempos de más de 100 minutos para acceder a estos servicios básicos, además de exponer a la poblacion palestina a enfrentamientos con los colonos israelíes.

Con todo, y a pesar de las limitaciones el estudio ha alcanzado sus objetivos. Si bien no hemos profundizado todo lo posible en la descripción de los resultados, cierto es que el trabajo se centraba en plantear un modelo metodológico para analizar el riesgo de protección. Para posteriores trabajos, la obtención de bases de datos más sólidas, e incluso extraídas de herramientas diseñadas específicamente para el propósito, podría proveer resultados más relevantes. Sobre semejante estudio sería recomendable adentrarse con mayor profundidad en la descripción e interpretación de resultados. Cabe destacar que el contexto palestino es quizás uno de los más complejos y particulares de la acción humanitaria. Mientras que el método en sus líneas principales es susceptible de ser aplicado en otros contextos humanitarios, el detalle de los resultados y su interpretación puede variar. Esto en cualquier caso no es algo indeseable, y mostraría la localización del análisis a las particularidades de cada contexto. Finalmente, si bien hemos traído en profundidad la dualidad entre funcionalismo –predicción– y estructuralismo –prospectiva– es cierto que nuestros métodos de análisis no han ahondado en estos tipos de análisis. No obstantes, lo que aquí planteamos es un paso previo que sienta las bases para aunar descriptivo y explicativo como paso previo para una análisis combinado de predicción y prospectiva.
